modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="bbf"
version="1.0.0"
displayName="BBF"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="LocalUser, MCreator"

[[dependencies.bbf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




